config/routes.rb
Rails.application.routes.draw do
  get '/search' => 'search#search'
  devise_for :users
  resources :users,only: [:show,:index,:edit,:update]
  resources :books do
  	resource :favorites, only: [:create, :destroy]
  	resources :book_comments, only: [:create, :destroy]
  	
  end
  resources :users do
  	member do
  	  get :following, :followers
  	end
  end
  resources :relationships, only: [:create, :destroy]
  root 'home#top'
  get 'home/about'

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
  	@model = params["search"]["model"]
  	@content = params["search"]["content"]
  	@how = params["search"]["how"]
  	@datas = search_for(@how, @model, @content)
  end

  private
  def match(model, content)
  	if model == 'user'
      User.where(name: content)
    elsif model == 'book'
    	Book.where(title: content)
    end
  end

  def forward(model, content)
  	if model =='user'
  		User.where("name LIKE ?", "#{content}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "#{content}%")
    end
  end

  def backward(model, content)
  	if model == 'user'
  	  User.where("name LIKE ?", "%#{content}")
  	elsif model =='book'
  	  Book.where("title LIKE ?", "%#{content}")
  	end
  end

  def partical(model, content)
  	if model =='user'
  		User.where("name LIKE ?", "%#{content}%")
    elsif model =='book'
      Book.where("title LIKE ?", "%#{content}%")
    end
  end

  def search_for(how, model, content)
  	case how
  	when 'match'
  	  match(model, content)
  	when 'forward'
  	  forward(model, content)
  	when 'backward'
  	  backward(model content)
  	when 'partical'
  	  partical(model, content)
  	end
  end
  
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/search.html.erb
<% if @model == 'book' %>
<!--books一覧 -->
	<h2>Books search for <%= @content %></h2>
	<table class="table table-hover table-inverse">
		<thead>
			<tr>
				<th></th>
				<th>Title</th>
				<th>Opinion</th>
				<th colspan="3"></th>
			</tr>
		</thead>

		<tbody>
			<% @datas.each do |data| %>

			<tr>
				<td>
					<%= link_to user_path(data.user) do %>
						<%= attachment_image_tag(data.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
					<% end %>
				</td>
				<td><%= link_to data.title, book_path(data), class: "data_#{data.id}" %></td>
				<td><%= data.body %></td>
				
			</tr>
			<% end %>
		</tbody>
	</table>
<% elsif @model == 'user' %>
<!-- Users一覧 -->
    <h2>Users search for <%= @content %></h2>
		<table class="table">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @datas.each do |data| %>
				<tr>
					<td><%= attachment_image_tag(data, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
					<td><%= data.name %></td>
					<td><%= link_to "Show", user_path(data), class: "data_#{data.id}" %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
<% end %>