config/routes.rb
Rails.application.routes.draw do
  get '/search' => 'search#search'
  devise_for :users
  resources :users,only: [:show,:index,:edit,:update]
  resources :books do
  	resource :favorites, only: [:create, :destroy]
  	resources :book_comments, only: [:create, :destroy]
  	
  end
  resources :users do
  	member do
  	  get :following, :followers
  	end
  end
  resources :relationships, only: [:create, :destroy]
  root 'home#top'
  get 'home/about'

end

app/models/book.rb
class Book < ApplicationRecord
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
	belongs_to :user
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	def favorited_by?(user)
	  favorites.where(user_id: user.id).exists?
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 before_action :authenticate_user!
  def show
    @ibook = Book.find(params[:id])
    @book = Book.new
    @user = @book.user
    @book_comment = BookComment.new
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
       render "edit"
    else
      redirect_to books_path
    end
  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title,:body)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %>
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">

		<h1>Editing Book</h1>
		<% if @book.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

              <ul>
                <% @book.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

		<%= render "books/newform", book: @book %>
		<%= link_to "Show", book_path(@book), class: "book_#{@book.id}" %>
		<%= link_to "Back", books_path, class: "back" %>

	</div>
	<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
        <% if @book.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

              <ul>
                <% @book.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>
		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to user_path(book.user) do %>
							<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
					<td class="inline-meta">
						By<%- book.user.name %></td>
					<td><%= link_to "#{book.book_comments.count}コメント", book_path(book) %></td>
					<% if book.favorited_by?(current_user) %>
					<td>
					  <%= link_to book_favorites_path(book), method: :delete do %>
					    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
					    <%= book.favorites.count %> いいね
					    <% end %>
					</td>
					<% else %>
					<td>
						<%= link_to book_favorites_path(book), method: :post do %>
						<i class="fa fa-heart-o" aria-hidden="true"></i>
						<%= book.favorites.count %>いいね
						<% end %>
					</td>
					<% end %>
					<% if book.user.id ==current_user.id %>
                    <td>
                      <%= link_to "Edit", edit_book_path(book),class: "btn-sm btn-success" %>
                      </td>
                      <% end %>
                      <% if book.user.id ==current_user.id %>
                    <td><%= link_to "Destroy", book_path(book), class: "btn-sm btn-danger",  method: :delete, "data-confirm" => "本当に消しますか?"  %></td>
                    <% end %>
				</tr>
				<% end %>
			</tbody>
		</table>

		<!--books一覧 -->


	</div>
</div>

app/views/books/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
				<tr>
					<td>
						<%= link_to user_path(@ibook.user) do %>
							<%= attachment_image_tag(@ibook.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
						<%= @ibook.user.name %>
						<% end %>
					</td>
					<td><%= link_to @ibook.title, book_path(@ibook) %></td>
					<td><%= @ibook.body %></td>
					<td><i class="fa fa-comment"></i></td>
					<td><a href="#comments"><%= @ibook.book_comments.count %></td>
                    <div class="comment-list bt style-2" class="comments">
					  <td class="float-wrapper"><h2 class="comment-count"><%= @ibook.book_comments.count %>件コメント</h2></td>
					</div>
					<% if @ibook.favorited_by?(current_user) %>
					<td>
					  <%= link_to book_favorites_path(@ibook), method: :delete do %>
					    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
					    <%= @ibook.favorites.count %> いいね
					    <% end %>
					</td>
					<% else %>
					<td>
						<%= link_to book_favorites_path(@ibook), method: :post do %>
						<i class="fa fa-heart-o" aria-hidden="true"></i>
						<%= @ibook.favorites.count %>いいね
						<% end %>
					</td>
					<% end %>
					<% if @ibook.user.id ==current_user.id %>
					<td><%= link_to "Edit", edit_book_path(@ibook), class: "btn-sm btn-success edit_book_#{@ibook.id}" %></td>
					<td><%= link_to "Destroy", book_path(@ibook), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@ibook.id}" %></td>
					<% end %>
				</tr>
			</table>
			<ol>
			  <% @ibook.book_comments.each do |book_comment| %>
			  <li class="comment">
			  	<div class="comment-body bb">
			  	  <div class="comment-avatar">
			  	  	<div class="avatar">
			  	  	  <%= attachment_image_tag(@ibook.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %>
			  	  	</div>
			  	  </div>
			  	  <div class="comment-text">
			  	  	<div class="comment-author clearfix">
			  	  	  <a href="#" class="link-author"><%= book_comment.user.name %></a>
			  	  	  <span class="comment-meta">
			  	  	    <span class="comment-date"><%= book_comment.created_at.strftime('%Y/%m/%d') %></span>
			  	  	  </span>
			  	  	</div>
			  	  	<div class="comment-entry"><%= book_comment.comment %></div>
			  	  	<% if book_comment.user == current_user %>
				  	  	<div>
				  	  	  <%= link_to "削除", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-danger pull-right" %>
				  	  	</div>
			  	  	<% end %>
			  	  	</div>
			  	  </div>
			  	
			  </li>
			  <% end %>
			</ol>
			<%= form_for [@ibook, @book_comment] do |f| %>
			  <div class="row">
			  	<div class="col-sm-12">
			  	  <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
			  	</div>
			  </div>
			  <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
			  <% end %>

	</div>
</div>